name: ilimbilim

on:
  push:
    branches: [ main ] # Trigger on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest # Use an Ubuntu runner

    steps:
    - uses: actions/checkout@v4 # Checkout your repository

    - name: Build APK
      uses: digreatbrian/buildozer-action@v
      with:
        python-version: 3.9 # Specify your Python version
        buildozer-cmd: buildozer -v android debug # Buildozer command

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: kivy-apk
        path: ./bin/*.apk # Path to your generated APK
